### ISSUE TITLE
Side chain prediction in presence of ligand

### ISSUE THREAD

**Issue by djcole56** [thuxugang/opus_rota5#1]
I enjoyed reading your paper. I see in Table 3 that opus-rota5 is able to take into account the ligand 3D coordinates when predicting side chain conformations. Can you provide an example of how to run the code for this case please?

**Comment by thuxugang** [comment]
Thank you for your interest. You can incorporate the coordinates of the ligand into the existing protein PDB file. The attachment file serves as an example for your reference.
[7br3_prot.pdb.txt](https://github.com/user-attachments/files/16705772/7br3_prot.pdb.txt)

**Comment by djcole56** [comment]
Many thanks for your reply! That almost worked, except I get an Assertion error from L309 of unet.py when a ligand is present:
```
assert seq_len == i + 1
```
if I comment that line out, everything appears to complete successfully. From the tests we've run today, it appears that the ligand information is taken into account in the side chain placement successfully. Just checking it's ok to remove that check? Thanks!

**Comment by thuxugang** [comment]
Sorry about this, you can just remove this assertion. The sorted_residues array encapsulates the combined lengths of both the protein and the ligand, we can safely disregard the construction for ligand side chains.

**Comment by djcole56** [comment]
Great, thanks for your help! That resolves it then
